### ISSUE TITLE
哥，我这几步不会做

### ISSUE THREAD

**Issue by 14790897** [iamshaynez/telegram-assistant#1]
需要开启 Worker 的 Router 并绑定在 TelegramBot 的 Webhook 上。
TelegramBot 的菜单需要手工添加和配置。
需要配置环境变量（加密）
TG_BOT_TOKEN
TG_CHAT_ID

**Comment by iamshaynez** [comment]
需要开启 Worker 的 Router 并绑定在 TelegramBot 的 Webhook 上。
-- 手工调用 https://api.telegram.org/bot{my_bot_token}/setWebhook?url={url_to_send_updates_to}

TelegramBot 的菜单需要手工添加和配置。
-- 去 BotFather 那边 Edit Bot，然后添加菜单

需要配置环境变量（加密）
TG_BOT_TOKEN
TG_CHAT_ID
-- 在 Cloudflare 的控制台里添加环境变量（用 wrangler 命令行也可以）

**Comment by 14790897** [comment]
![image](https://github.com/iamshaynez/telegram-assistant/assets/121866954/cf97c95c-102e-447c-ae60-6e41181fce7a)
配置好了

**Comment by iamshaynez** [comment]
谢谢感兴趣～

**Comment by iamshaynez** [comment]
在 Readme 里增加了如何维护网关KV 里面的 metadata，这样提示信息会稍微好看一点（否则默认就是 counter 这样的应用 code）。请参考。
